#!/usr/bin/env python3
"""Derives the per-module publish set for a dev.sajidali fork release from the release ledger.

The ledger (compose-tvos-redirect/tools/release/release-ledger/<version>.json, generated by
tools/release/ledger.py) is the only source of versions. Nothing in this repository types a
version by hand; publish-tvos-fork.sh and stage-central-bundle.sh both eval the output of
this script.

Publish set = every ledger artifact whose upstream `tvos.usable` is EMPTY (an artifact that
advertises tvOS targets whose leaf modules 404 on Central counts as unusable and therefore
needs a fork build), minus artifacts whose `forkOnCentral` is already true, minus the
NEVER_PUBLISH list below. Each member is resolved to the Gradle project in this repository
that publishes it; members with no project here (the compose-multiplatform repo's
`components-*` modules) are reported separately and never handed to Gradle.

Usage:
  publish_set.py --ledger <json> [--only-group <org.jetbrains group> ...]
                 [--include-tests] [--include-tooling-preview] [--ignore-central]
                 [--format table|json|shell] [--repo-root <path>]

`--format shell` prints bash assignments (arrays, bash 3.2 compatible) for the scripts.
Exit is non-zero when any library key the build registers is missing from the ledger.
"""

import argparse
import json
import os
import re
import sys

# Library keys registered in buildSrc/public/.../JetBrainsPublication.libraryToComponents
# that are JetBrains-published (and so present in the ledger). Every one of them must carry
# a version on every Gradle invocation: JetBrainsVersions.versionOf() silently returns
# 9999.0.0-SNAPSHOT for a key without a -Pjetbrains.publication.version.<KEY> property, and
# that version then leaks into the published module metadata as a dependency edge.
# TV_MATERIAL is registered in the build as well but is androidx.tv, not a JetBrains
# library, so it is not in the ledger and not passed; nothing in the publish set depends on it.
REQUIRED_LIBRARIES = (
    "COMPOSE",
    "COMPOSE_MATERIAL3",
    "COMPOSE_MATERIAL3_ADAPTIVE",
    "LIFECYCLE",
    "NAVIGATION",
    "NAVIGATION_3",
    "NAVIGATION_EVENT",
    "SAVEDSTATE",
    "WINDOW",
)

# Artifacts the fork never republishes, keyed (group, artifact) -> flag that re-enables them
# (None = no override). ui-test/ui-test-junit4 are test harnesses a tvOS app never ships;
# ui-tooling and ui-tooling-data are JVM_BASED-only in JetBrainsPublication and have no tvOS
# variant to add; ui-tooling-preview is an annotation-only module that is not required by any
# tvOS consumer unless a downstream module explicitly needs the dev.sajidali twin.
NEVER_PUBLISH = {
    ("org.jetbrains.compose.ui", "ui-test"): "--include-tests",
    ("org.jetbrains.compose.ui", "ui-test-junit4"): "--include-tests",
    ("org.jetbrains.compose.ui", "ui-tooling"): None,
    ("org.jetbrains.compose.ui", "ui-tooling-data"): None,
    ("org.jetbrains.compose.ui", "ui-tooling-preview"): "--include-tooling-preview",
}

JB_COMPOSE_PREFIX = "org.jetbrains.compose."
JB_ANDROIDX_PREFIX = "org.jetbrains.androidx."
VERSION_PROPERTY_PREFIX = "-Pjetbrains.publication.version."


def die(msg):
    sys.stderr.write("publish_set.py: error: %s\n" % msg)
    sys.exit(1)


def project_path_for(group, artifact):
    # Inverse of JetBrainsPublication.mavenGroupFor: org.jetbrains.compose.X.Y:Z is
    # :compose:X:Y:Z and org.jetbrains.androidx.X:Z is :X:Z.
    if group.startswith(JB_COMPOSE_PREFIX):
        return ":compose:%s:%s" % (group[len(JB_COMPOSE_PREFIX):].replace(".", ":"), artifact)
    if group.startswith(JB_ANDROIDX_PREFIX):
        return ":%s:%s" % (group[len(JB_ANDROIDX_PREFIX):].replace(".", ":"), artifact)
    return None


def load_settings_projects(repo_root):
    # includeProject(":path") is a real project; includeProject(":path", "mpp/stub-project")
    # is a stub that publishes nothing.
    real, stubs = set(), set()
    settings = os.path.join(repo_root, "settings.gradle")
    if not os.path.isfile(settings):
        return real, stubs
    pat = re.compile(r'^\s*includeProject\(\s*"(:[^"]+)"\s*(?:,\s*"([^"]*)")?')
    with open(settings) as fh:
        for line in fh:
            m = pat.match(line)
            if not m:
                continue
            if m.group(2) and "stub-project" in m.group(2):
                stubs.add(m.group(1))
            else:
                real.add(m.group(1))
    return real, stubs


def resolve_project(repo_root, real_projects, stub_projects, group, artifact):
    path = project_path_for(group, artifact)
    if path is None:
        return None, "group %s has no project-path rule" % group
    rel = path.lstrip(":").replace(":", os.sep)
    has_build = any(
        os.path.isfile(os.path.join(repo_root, rel, name))
        for name in ("build.gradle", "build.gradle.kts")
    )
    if path in stub_projects:
        return None, "%s is a stub project in settings.gradle" % path
    if path not in real_projects:
        return None, "%s is not included in settings.gradle" % path
    if not has_build:
        return None, "%s has no build.gradle in this repo" % path
    if os.path.basename(rel) != artifact:
        return None, "%s directory name does not match artifact id" % path
    return path, None


def derive(ledger, args, repo_root):
    libs = ledger.get("libraries") or {}
    missing = [k for k in REQUIRED_LIBRARIES if not (libs.get(k) or {}).get("jetbrainsVersion")]
    if missing:
        die("ledger %s has no jetbrainsVersion for: %s" % (args.ledger, ", ".join(missing)))
    versions = {k: libs[k]["jetbrainsVersion"] for k in REQUIRED_LIBRARIES}
    for k in sorted(libs):
        if k not in versions:
            die("ledger library %s is not a key this build registers; refusing to guess" % k)

    real_projects, stub_projects = load_settings_projects(repo_root)
    only = set(args.only_group or [])
    publish, excluded, unbuildable = [], [], []
    for a in ledger["artifacts"]:
        entry = {
            "group": a["group"],
            "artifact": a["artifact"],
            "version": a["version"],
            "library": a["library"],
        }
        if versions.get(a["library"]) != a["version"]:
            die("%s:%s is at %s but ledger library %s says %s"
                % (a["group"], a["artifact"], a["version"], a["library"], versions.get(a["library"])))
        if only and a["group"] not in only:
            excluded.append(dict(entry, reason="not in --only-group"))
            continue
        usable = (a.get("tvos") or {}).get("usable") or []
        advertised = (a.get("tvos") or {}).get("advertised") or []
        if usable:
            excluded.append(dict(entry, reason="upstream tvOS usable (%s)" % ",".join(usable)))
            continue
        flag = NEVER_PUBLISH.get((a["group"], a["artifact"]), "absent")
        if flag != "absent":
            enabled = (flag == "--include-tests" and args.include_tests) or (
                flag == "--include-tooling-preview" and args.include_tooling_preview)
            if not enabled:
                excluded.append(dict(entry, reason="NEVER_PUBLISH" + (
                    " (override: %s)" % flag if flag else "")))
                continue
        if a.get("forkOnCentral") and not args.ignore_central:
            excluded.append(dict(entry, reason="dev.sajidali twin already on Central"))
            continue
        why = "no upstream tvOS" if not advertised else (
            "advertised %s but leaf modules missing upstream" % ",".join(advertised))
        project, problem = resolve_project(repo_root, real_projects, stub_projects,
                                           a["group"], a["artifact"])
        if project is None:
            unbuildable.append(dict(entry, reason=why, problem=problem))
            continue
        publish.append(dict(entry, project=project, reason=why))

    return {
        "ledger": os.path.abspath(args.ledger),
        "cmpVersion": ledger.get("cmpVersion"),
        "kotlin": ledger.get("kotlin"),
        "versions": versions,
        "gradleVersionArgs": ["%s%s=%s" % (VERSION_PROPERTY_PREFIX, k, v)
                              for k, v in versions.items()],
        "libraries": sorted({p["library"] for p in publish}),
        "publish": publish,
        "unbuildable": unbuildable,
        "excluded": excluded,
    }


def coord(e):
    return "%s:%s:%s" % (e["group"], e["artifact"], e["version"])


def print_table(result, out=sys.stdout):
    w = out.write
    w("ledger      %s\n" % result["ledger"])
    w("cmp/kotlin  %s / %s\n" % (result["cmpVersion"], result["kotlin"]))
    w("versions    %s\n" % " ".join("%s=%s" % kv for kv in result["versions"].items()))
    w("\nPUBLISH (%d module%s)\n" % (len(result["publish"]), "" if len(result["publish"]) == 1 else "s"))
    if not result["publish"]:
        w("  (none)\n")
    for p in result["publish"]:
        w("  %-60s %-26s %-45s %s\n" % (coord(p), p["library"], p["project"], p["reason"]))
    if result["unbuildable"]:
        w("\nNEEDS A FORK BUT NOT BUILT FROM THIS REPO (%d)\n" % len(result["unbuildable"]))
        for u in result["unbuildable"]:
            w("  %-60s %-26s %s; %s\n" % (coord(u), u["library"], u["reason"], u["problem"]))
    w("\nEXCLUDED (%d)\n" % len(result["excluded"]))
    for e in result["excluded"]:
        w("  %-60s %-26s %s\n" % (coord(e), e["library"], e["reason"]))
    w("\nGradle version properties (pass ALL of them on every invocation):\n")
    for arg in result["gradleVersionArgs"]:
        w("  %s\n" % arg)


def sq(s):
    return "'" + s.replace("'", "'\\''") + "'"


def print_shell(result, out=sys.stdout):
    w = out.write
    w("LEDGER_FILE=%s\n" % sq(result["ledger"]))
    w("LEDGER_CMP_VERSION=%s\n" % sq(result["cmpVersion"] or ""))
    w("LEDGER_KOTLIN=%s\n" % sq(result["kotlin"] or ""))
    w("VERSION_PROPS=(%s)\n" % " ".join(sq(a) for a in result["gradleVersionArgs"]))
    w("PUBLISH_LIBRARIES=%s\n" % sq(",".join(result["libraries"])))
    w("PUBLISH_MODULES=(%s)\n" % " ".join(sq(p["project"]) for p in result["publish"]))
    w("PUBLISH_COORDS=(%s)\n" % " ".join(sq(coord(p)) for p in result["publish"]))
    w("UNBUILDABLE_COORDS=(%s)\n" % " ".join(sq(coord(u)) for u in result["unbuildable"]))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", default=os.environ.get("TVOS_LEDGER"),
                    help="release ledger JSON (default: $TVOS_LEDGER)")
    ap.add_argument("--only-group", action="append", metavar="GROUP",
                    help="restrict to this org.jetbrains group (repeatable)")
    ap.add_argument("--include-tests", action="store_true",
                    help="allow ui-test and ui-test-junit4 into the set")
    ap.add_argument("--include-tooling-preview", action="store_true",
                    help="allow ui-tooling-preview into the set")
    ap.add_argument("--ignore-central", action="store_true",
                    help="keep artifacts whose dev.sajidali twin is already on Central (full rebuild view)")
    ap.add_argument("--format", choices=("table", "json", "shell"), default="table")
    ap.add_argument("--repo-root", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    args = ap.parse_args()
    if not args.ledger:
        die("--ledger <json> (or TVOS_LEDGER) is required")
    if not os.path.isfile(args.ledger):
        die("ledger not found: %s" % args.ledger)
    with open(args.ledger) as fh:
        ledger = json.load(fh)
    result = derive(ledger, args, os.path.abspath(args.repo_root))
    if args.format == "json":
        json.dump(result, sys.stdout, indent=2)
        sys.stdout.write("\n")
    elif args.format == "shell":
        print_shell(result)
    else:
        print_table(result)


if __name__ == "__main__":
    main()
