name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - jb-main
      - integration

jobs:
  compose-native-publish:
    runs-on: macos-26
    name: Darwin + Native Linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Setup Xcode
        uses: ./.github/actions/setup-xcode

      - name: Dry Publish
        run: |
          ./gradlew publishComposeJb -Pcompose.platforms=macos,ios,tvos,watchos,linux,mingw \
            --no-daemon --stacktrace

      - name: Demos
        run: |
          ./gradlew \
            :compose:mpp:demo:linkDebugExecutableMacosArm64 \
            :compose:mpp:demo:linkDebugExecutableIosArm64 \
            :compose:mpp:demo:linkDebugExecutableIosSimArm64 \
            --no-daemon --stacktrace

  compose-web-publish:
    runs-on: ubuntu-24.04
    name: Web
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Dry Publish
        run: |
          ./gradlew publishComposeJb -Pcompose.platforms=web \
            --no-daemon --stacktrace

      - name: Demos
        run: |
          ./gradlew \
            :compose:mpp:demo:compileKotlinJs \
            :compose:mpp:demo:compileKotlinWasmJs \
            --no-daemon --stacktrace

  compose-jvm-publish:
    runs-on: ubuntu-24.04
    name: JVM
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Dry Publish
        run: |
          ./gradlew publishComposeJb -Pcompose.platforms=jvm,android \
            --no-daemon --stacktrace

      - name: Demos
        run: |
          ./gradlew \
            :compose:mpp:demo:desktopMainClasses \
            :compose:desktop:desktop:desktop-samples:jvmMainClasses \
            --no-daemon --stacktrace
